version: '3.8'

services:
  backup:
    build: .
    container_name: volume-backup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/docker-volumes:ro
      - /var/backups:/var/backups
    restart: always
